@echo off
REM Mermaid Diagram Conversion Script
REM Converts Mermaid diagrams to PDF and SVG formats using Docker
REM Generated by Claude, Fixed by Skylar Scott

setlocal enabledelayedexpansion

echo Searching for Mermaid files in docs\mermaid...
echo.

for %%f in (docs\mermaid\*.mmd docs\mermaid\*.mermaid) do (
    if exist "%%f" (
        set "filename=%%~nf"
        echo Converting !filename!...

        echo   - Creating PDF...
        docker run --rm -v %cd%:/data minlag/mermaid-cli -i "docs/mermaid/%%~nxf" -o "docs/pdf/!filename!.pdf" -b white

        echo   - Creating SVG...
        docker run --rm -v %cd%:/data minlag/mermaid-cli -i "docs/mermaid/%%~nxf" -o "docs/img/!filename!.svg" -b white

        echo   Done: docs\pdf\!filename!.pdf ^& docs\img\!filename!.svg
        echo.
    )
)

echo Conversion complete!
